### ISSUE TITLE
Create a Javascript object to represent the JSON object the hours api returns

### ISSUE THREAD

**Issue by hab278** [Amay22/hours_test#1]
The libcal hours api returns an array of JSON objects, turn those JSON objects into Javascripts objects by writing up code of a Javascript object (in coffeescript!). It'd be awesome to have that object to have easy access methods to its variables.

**Comment by Amay22** [comment]
Done on https://github.com/Amay22/CS_testing/blob/master/test1.coffee
Just requires revisions now.
